[tools]
node = "latest"

antigravity-cli = "latest"
ast-grep = "latest"
eza = "latest"
fd = "latest"
fzf = "latest"
ghq = "latest"
github-cli = "latest"
jq = "latest"
pi = "latest"
ripgrep = "latest"
starship = "latest"
yazi = "latest"
yt-dlp = "latest"

[settings]
experimental = true
idiomatic_version_file_enable_tools = []
