#!/usr/bin/env zsh

autoload -Uz compinit; compinit
autoload -Uz colors; colors

zstyle ':completion::complete:*' use-cache true
zstyle ':completion:*:commands' rehash 1
zstyle ':completion:*:default' menu select=2
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Z}'
zstyle ':completion:*' list-colors "${LS_COLORS}"

setopt no_beep
setopt auto_cd
setopt auto_pushd
setopt auto_menu
setopt list_packed
setopt list_types
setopt pushd_ignore_dups
setopt correct
setopt magic_equal_subst
setopt complete_aliases
setopt extended_glob
setopt nonomatch
setopt share_history
setopt extended_history
setopt inc_append_history
setopt hist_ignore_dups
setopt hist_ignore_space
setopt hist_ignore_all_dups
setopt hist_reduce_blanks

unsetopt caseglob
unsetopt promptcr

typeset -U path PATH

export TZ="Asia/Tokyo"
export LANG="ja_JP.utf8"
export LESS="-R"
export EDITOR="vim"
export FCEDIT="vim"

export HISTFILE="${HOME}/.zsh_history"
export HISTSIZE=100000
export SAVEHIST=100000

export FZF_DEFAULT_OPTS="--height 40% --ansi --cycle --reverse --select-1 --exit-0 --bind=tab:down --bind=btab:up"

export XDG_CONFIG_HOME="${HOME}/.config"

export GOPATH="${HOME}/.go"
export PATH="${GOPATH}/bin:${PATH}"

if [[ "${OSTYPE}" == darwin* ]]; then
  eval "$(/usr/local/bin/brew shellenv)"
elif [[ "${OSTYPE}" == linux* ]]; then
  eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
fi

eval "$(rtx activate zsh)"
eval "$(starship init zsh)"

source "${HOME}/.cargo/env"

source "${XDG_CONFIG_HOME}/zsh/alias.zsh"
source "${XDG_CONFIG_HOME}/zsh/function.zsh"
source "${XDG_CONFIG_HOME}/zsh/plugin/zsh-completions/zsh-completions.plugin.zsh"
source "${XDG_CONFIG_HOME}/zsh/plugin/zsh-autosuggestions/zsh-autosuggestions.plugin.zsh"
source "${XDG_CONFIG_HOME}/zsh/plugin/zsh-syntax-highlighting/zsh-syntax-highlighting.plugin.zsh"
source "${XDG_CONFIG_HOME}/zsh/plugin/zsh-history-substring-search/zsh-history-substring-search.plugin.zsh"

zle -N fzf_history
bindkey '^r' fzf_history

zle -N fzf_ghq
bindkey '^g' fzf_ghq

zle -N fzf_switch
bindkey '^b' fzf_switch
