#!/usr/bin/env zsh

autoload -Uz compinit; compinit

zstyle ':completion::complete:*' use-cache true
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Z}'

setopt auto_pushd
setopt pushd_ignore_dups

setopt extended_history
setopt hist_ignore_all_dups
setopt hist_ignore_space
setopt hist_reduce_blanks
setopt inc_append_history

setopt list_packed
setopt list_types
setopt magic_equal_subst

setopt no_beep
setopt extended_glob
setopt nonomatch

export TZ="Asia/Tokyo"
export LANG="ja_JP.UTF8"
export LESS="-R"
export EDITOR="vim"
export FCEDIT="vim"

export HISTFILE="${HOME}/.zsh_history"
export HISTSIZE=100000
export SAVEHIST=100000

export DOTFILES=${DOTFILES:="${HOME}/work/github.com/nazna/dotfiles"}
export XDG_CONFIG_HOME=${XDG_CONFIG_HOME:="${HOME}/.config"}

export DO_NOT_TRACK=1
export DISABLE_TELEMETRY=1

typeset -U path PATH

path+=("${HOME}/.local/bin")

eval "$(mise activate zsh)"
eval "$(starship init zsh)"

source "${XDG_CONFIG_HOME}/zsh/alias.zsh"
source "${XDG_CONFIG_HOME}/zsh/function.zsh"
source "${XDG_CONFIG_HOME}/zsh/completions/zsh-completions.plugin.zsh"
source "${XDG_CONFIG_HOME}/zsh/autosuggestions/zsh-autosuggestions.plugin.zsh"
source "${XDG_CONFIG_HOME}/zsh/syntax-highlighting/zsh-syntax-highlighting.plugin.zsh"
